### ISSUE TITLE
Management Client Crash when Creating Live stream

### ISSUE THREAD

**Issue by EddieCutts** [ORBNETSYS/StreamingEngine-Public#9]
Version 2.9.1 fresh install and Management Client running as Adminstrator

Succesfully import client secret and can reconnect to the API - 
enter stream name and then client 'Create broadcast and start streaming' we then see the following crash.

Exception type:        System.NullReferenceException
Exception message:     Object reference not set to an instance of an object.
Exception target site: A
   at OrbStreamingEngineMilestonePlugins.Admin.AdminTabCameraUserControl.A()
   at OrbStreamingEngineMilestonePlugins.Admin.AdminTabCameraUserControl.A(Object , ElapsedEventArgs )
   at OrbStreamingEngineMilestonePlugins.Admin.AdminTabCameraUserControl.B.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** System Info **************

Date and Time:         20/02/2022 15:05:43
Machine Name:          ***-***-***
IP address:            fe80::94ce:7355:a451:9562%14 (***-***-***)
Current User:          ***-***-***\ORBNET

**Comment by EricBourque** [comment]
I think this was fixed in the last update right?
